apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hello-static.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "hello-static.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
{{ toYaml .Values.storage.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
{{- end }}
